name: Freezer
version: 0.0.1
main: com.jackburkhardt.plugins.freezer.Freezer
author: TwelvePointFive
description: It freezes things. Yeah.
website: https://jackburkhardt.com
commands:
  freeze:
    description: Freezes the game.
    permission: freeze.permission
    permission-message: You don't have permission to use this command.
permissions:
  freeze.permission:
    default: op
  freeze.exempt:
    default: op